const Analysis = {
  totalMinutes(){return (DB.user().studyLogs||[]).reduce((x,l)=>x+(+l.minutes||0),0)},
  averageNet(){const x=DB.user().exams||[];return x.length?x.reduce((a,b)=>a+b.total,0)/x.length:0},
  streak(){const days=new Set((DB.user().studyLogs||[]).filter(x=>x.minutes>0).map(x=>new Date(x.date).toDateString()));let n=0,d=new Date();while(days.has(d.toDateString())){n++;d.setDate(d.getDate()-1)}return n},
  daily(){const data=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);const mins=(DB.user().studyLogs||[]).filter(l=>new Date(l.date).toDateString()===d.toDateString()).reduce((a,l)=>a+(+l.minutes||0),0);data.push({label:d.toLocaleDateString('tr-TR',{weekday:'short'}),value:mins})}return data},
  range(days){const logs=DB.user().studyLogs||[],now=new Date(),data=[],key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(days===365){for(let month=0;month<12;month++){const d=new Date(now.getFullYear(),month,1),value=logs.filter(l=>{const x=new Date(l.date);return x.getFullYear()===d.getFullYear()&&x.getMonth()===month}).reduce((a,l)=>a+(+l.minutes||0),0);data.push({date:`${d.getFullYear()}-${String(month+1).padStart(2,'0')}`,label:d.toLocaleDateString('tr-TR',{month:'short'}),value})}return data}const first=days===30?new Date(now.getFullYear(),now.getMonth(),1):new Date(now.getFullYear(),now.getMonth(),now.getDate()-6),count=days===30?new Date(now.getFullYear(),now.getMonth()+1,0).getDate():7;for(let i=0;i<count;i++){const d=new Date(first);d.setDate(first.getDate()+i);const dayKey=key(d),value=logs.filter(l=>String(l.date).slice(0,10)===dayKey).reduce((a,l)=>a+(+l.minutes||0),0);data.push({date:dayKey,label:days===7?d.toLocaleDateString('tr-TR',{weekday:'short'}):String(i+1),value})}return data},
  weakTopics(){const all=[...(DB.user().mistakes||[]),...(DB.user().exams||[]).filter(e=>e.weakTopic).map(e=>({topic:e.weakTopic,subject:e.weakSubject||'Genel'}))],map={};all.forEach(x=>{const key=`${x.subject} • ${x.topic}`;map[key]??={subject:x.subject,topic:x.topic,count:0};map[key].count++});return Object.values(map).sort((a,b)=>b.count-a.count)},
  examTrend(type='Tümü'){const x=(DB.user().exams||[]).filter(e=>type==='Tümü'||(e.examType||'TYT')===type).sort((a,b)=>new Date(a.date)-new Date(b.date)).slice(-3);if(x.length<2)return {label:'Veri bekleniyor',delta:0,exams:x};const delta=x[x.length-1].total-x[0].total;return {label:delta>0.5?'Yükseliyor':delta<-.5?'Düşüyor':'Sabit',delta,exams:x}},
  lessonWeakness(){const map={};(DB.user().exams||[]).forEach(e=>['turkce','mat','fen','sosyal'].forEach(k=>{const wrong=+e[k+'Y']||0;map[k]=(map[k]||0)+wrong}));return Object.entries(map).sort((a,b)=>b[1]-a[1])[0]},
  reviews(){const now=Date.now(),days=[1,3,7,14],out=[];(DB.user().mistakes||[]).filter(m=>!m.reviewed).forEach(m=>days.forEach(day=>{const due=new Date(m.createdAt+day*864e5);if(due<=now)out.push({...m,day,due})}));return out.sort((a,b)=>a.due-b.due)},
  badges(){const u=DB.user(),questions=(u.tasks||[]).filter(t=>t.done).length*10,avg=this.averageNet(),exams=(u.exams||[]).length,streak=this.streak();return [{icon:'🔥',name:'7 Gün Seri',text:'7 gün üst üste çalış',earned:streak>=7},{icon:'⚡',name:'1000 Soru',text:'1000 soru hedefi',earned:questions>=1000},{icon:'🎯',name:'İlk 80 Net',text:'80 net ortalamasına ulaş',earned:avg>=80},{icon:'🏁',name:'10 Deneme',text:'10 deneme kaydet',earned:exams>=10}]}
};
