const Auth = {
  toggle(register) { document.querySelector('#login-form').classList.toggle('hidden',register); document.querySelector('#register-form').classList.toggle('hidden',!register); },
  key(value){return String(value||'').trim().toLocaleLowerCase('tr-TR')},
  register(e) { e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)), users=DB.users(),name=String(f.name||'').trim(),username=String(f.username||'').trim(); if(!name||!username||String(f.password||'').length<4)return App.toast('Ad, kullanıcı adı ve en az 4 karakterlik şifre gir.'); if(users.some(u=>this.key(u.username)===this.key(username))) return App.toast('Bu kullanıcı adı zaten alınmış.'); DB.saveUsers([...users,DB.blank(name,username,f.password)]); DB.setCurrent(username); App.start(); },
  login(e) { e.preventDefault(); const f=Object.fromEntries(new FormData(e.target)), u=DB.users().find(u=>this.key(u.username)===this.key(f.username)&&u.password===f.password); if(!u)return App.toast('Kullanıcı adı veya şifre hatalı. Kullanıcı adında büyük/küçük harf fark etmez.'); DB.setCurrent(u.username); App.start(); },
  forgot(){App.modal('Şifreni yenile',`<form onsubmit="Auth.resetPassword(event)"><p class="form-note">Bu sürümde hesaplar cihazında saklanır. Aynı cihazdaki hesabının şifresini yenileyebilirsin.</p><label>Kullanıcı adı<input required name="username" autocomplete="username"></label><label>Yeni şifre<input required name="password" type="password" minlength="4" autocomplete="new-password"></label><label>Yeni şifre tekrar<input required name="again" type="password" minlength="4" autocomplete="new-password"></label><button class="btn primary wide">Şifreyi yenile</button></form>`,'form-modal')},
  resetPassword(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),user=DB.users().find(x=>this.key(x.username)===this.key(f.username));if(!user)return App.toast('Bu cihazda bu kullanıcı adıyla kayıtlı hesap bulunamadı.');if(String(f.password||'').length<4)return App.toast('Şifre en az 4 karakter olmalı.');if(f.password!==f.again)return App.toast('Şifreler aynı değil.');DB.saveUsers(DB.users().map(x=>x.username===user.username?{...x,password:f.password}:x));App.closeModal();this.toggle(false);const input=document.querySelector('#login-form [name="username"]');if(input)input.value=user.username;App.toast('Şifren yenilendi. Yeni şifrenle giriş yapabilirsin.');},
  logout() { DB.logout(); location.reload(); }
};
