const Subjects = {
  data: {
    'Türkçe': [['Sözcükte, Cümlede ve Paragrafta Anlam','Metin analizi, çıkarım ve anlam kurma becerileri.'],['Anlatım Biçimleri ve Düşünceyi Geliştirme Yolları','Yazarın anlatımını ve düşünce örgüsünü yorumla.'],['Ses Bilgisi, Yazım Kuralları ve Noktalama İşaretleri','Dilin ses ve yazım yapısı.'],['Sözcük Türleri','İsim, sıfat, zamir, zarf, edat, bağlaç ve ünlem.'],['Fiiller, Fiilimsiler ve Ek Eylem','Fiil yapıları ve görevleri.'],['Cümlenin Ögeleri ve Cümle Çeşitleri','Cümle yapısını çöz.'],['Anlatım Bozuklukları','Anlam ve yapı bozukluklarını fark et.']],
    'Matematik': [['Sayı Kümeleri, Temel Kavramlar ve Sayı Basamakları','Sayı yapısı ve basamak değerleri.'],['Üslü ve Köklü İfadeler','İfadeleri dönüştür ve yorumla.'],['Mutlak Değer, Çarpanlara Ayırma ve Özdeşlikler','Cebirsel işlem becerisi.'],['Oran-Orantı, Denklem ve Eşitsizlikler','Model kurma ve çözüm kümesi.'],['Problemler','Sayı, kesir, yaş, hareket, yüzde ve kâr-zarar.'],['Fonksiyonlar','Doğrusal, karesel, rasyonel ve ters fonksiyonlar.'],['Mantık ve Kümeler','Bağlaçlar, önermeler ve küme işlemleri.'],['Sayma, Olasılık ve İstatistik','Permütasyon, kombinasyon, olasılık ve veri araştırması.']],
    'Geometri': [['Doğruda ve Üçgende Açılar','Açı ilişkileri.'],['Üçgenler','Kenar-açı özellikleri ve alan.'],['Çokgenler ve Dörtgenler','Özel dörtgenler ve çokgenler.'],['Çember ve Daire','Açı, uzunluk ve alan.'],['Katı Cisimler','Prizma, piramit, silindir, koni ve küre.'],['Analitik Geometri','Doğru, uzaklık ve koordinat düzlemi.']],
    'Fizik': [['Fizik Bilimine Giriş ve Ölçme','Birimler ve fiziksel büyüklükler.'],['Madde ve Özellikleri / Akışkanlar','Madde ve akışkan davranışı.'],['Kuvvet ve Hareket','Hareketi grafiklerle modelle.'],['İş, Güç ve Enerji','Enerji dönüşümleri.'],['Isı, Sıcaklık ve Genleşme','Isı alışverişi.'],['Basınç ve Kaldırma Kuvveti','Sıvı-gaz basıncı.'],['Elektrik ve Manyetizma','Devreler ve manyetik olaylar.'],['Dalgalar ve Optik','Dalga, ışık ve görüntü.']],
    'Kimya': [['Kimya Bilimi ve Güvenlik','Güvenli kimya uygulamaları.'],['Atom ve Periyodik Sistem','Atom yapısı ve periyodik özellikler.'],['Kimyasal Türler Arası Etkileşimler','Bağlar ve etkileşimler.'],['Maddenin Halleri ve Karışımlar','Hâller, çözeltiler ve ayırma.'],['Kimyasal Tepkimeler ve Mol Kavramı','Tepkimeler ve hesaplamalar.'],['Asitler, Bazlar ve Tuzlar','pH ve günlük yaşam.'],['Sürdürülebilirlik ve Yeşil Kimya','Çevre kimyası yaklaşımları.']],
    'Biyoloji': [['Yaşam Bilimi ve Canlıların Ortak Özellikleri','Canlılık süreçleri.'],['Hücre','Yapı, organeller ve madde geçişleri.'],['Canlıların Sınıflandırılması','Canlı çeşitliliği.'],['Ekosistem Ekolojisi ve Çevre Sorunları','Ekosistem işleyişi.'],['Kalıtım ve Biyolojik Çeşitlilik','Kalıtım ilkeleri.']],
    'Tarih': [['Geçmişin İnşa Sürecinde Tarih','Tarih bilimi ve kaynaklar.'],['İlk Çağ ve Orta Çağ Medeniyetleri','Medeniyetlerin etkileşimi.'],['İslamiyet Öncesi Türk Tarihi','Türk dünyası.'],['İslam Medeniyetinin Doğuşu','Türklerin İslamiyet’i kabulü.'],['Türk-İslam Devletleri ve Osmanlı','Selçuklu, Osmanlı kuruluş ve yükselişi.']],
    'Coğrafya': [['Doğal Sistemler','İklim, yer şekilleri, su ve toprak.'],['Beşerî Sistemler','Nüfus, yerleşme ve göç.'],['Türkiye ve Ekonomik Faaliyetler','Mekânsal sentez ve üretim.'],['Çevre, Toplum ve Doğal Afetler','Çevresel sorunlar ve afetler.'],['Küresel Ortam ve Harita Bilgisi','Bölgeler, ülkeler ve harita.']],
    'Felsefe': [['Felsefenin Doğası ve Temel Problemleri','Sorgulama ve felsefi düşünce.'],['Varlık Felsefesi','Varlığı açıklayan yaklaşımlar.'],['Bilgi Felsefesi','Bilginin kaynağı ve sınırları.'],['Ahlak ve Siyaset Felsefesi','İyi, adalet ve toplum.'],['Din, Sanat ve Bilim Felsefesi','İnsan deneyimini sorgulama.']],
    'Din Kültürü': [['İnanç, İbadet ve Ahlak Esasları','İnanç ve ahlaki ilkeler.'],['Kur’an’a Göre Hz. Muhammed','Hayatı ve örnekliği.'],['İslam Düşüncesi ve Din-Kültür İlişkisi','Yorumlar, kültür ve düşünce.']]
  },
  status: ['Başlanmadı','Çalışılıyor','Tamamlandı'],
  progress(subject) { const u=DB.user(), list=this.data[subject]||[], done=list.filter(([n])=>u.subjects[n]==='Tamamlandı').length, working=list.filter(([n])=>u.subjects[n]==='Çalışılıyor').length; return Math.round((done+working*.5)/list.length*100)||0; }
};

const AytSubjects = {
  'Matematik': [['İstatistiksel Araştırma Süreci','İki nicel değişken, saçılım diyagramı ve korelasyon.'],['Geometrik Şekiller','Dörtgenler, çokgenler ve alan.'],['Trigonometri','Trigonometrik fonksiyonlar, grafikler ve denklemler.'],['Üstel ve Logaritmik Fonksiyonlar','Üstel-logaritmik fonksiyon, denklem ve eşitsizlik.'],['Fonksiyonlarda Bileşke','Bileşke fonksiyon ve cebirsel işlemler.']],
  'Fizik': [['Kuvvet ve Hareket','Newton yasaları, sürtünme ve çembersel hareket.'],['Elektrik ve Manyetizma','Elektrik alan, manyetik alan ve indüksiyon.'],['Optik','Ayna, kırılma, mercek ve görüntü.']],
  'Kimya': [['Enerji ve Tepkime Hızı','Entalpi, bağ enerjisi ve tepkime hızı.'],['Kimyasal Denge','Denge, asit-baz ve çözünürlük dengesi.'],['Sürdürülebilirlik','Nanoteknoloji, yeşil hidrojen ve mikroplastikler.']],
  'Biyoloji': [['Tepki','Sinir sistemi, hormonlar, hareket ve bağışıklık.'],['Homeostazi','Endokrin, dolaşım, solunum, boşaltım ve denge.']],
  'Edebiyat': [['Bir Diyeceğim Var!','Şiir, ahenk, söz sanatları ve inceleme.'],['Kültür Yolculuğu','Orhun Abideleri, Divânu Lugâti’t-Türk ve anı.'],['Yaşamın İzinde','Hikâye, roman ve metin tahlili.'],['Hayatın Aynası','Öğretici metinler ve metinler arası ilişkiler.']],
  'Tarih': [['Değişen Dünyada Osmanlı','1683-1789, Lale Devri ve Sanayi Devrimi.'],['Dönüşüm Sürecinde Osmanlı','1789-1908, Fransız İhtilali ve değişimler.'],['Savaşlar Sarmalında Osmanlı','1908-1918 ve I. Dünya Savaşı.']],
  'Coğrafya': [['Mekânsal Bilgi Teknolojileri','Web tabanlı CBS, harita okuma ve katmanlar.'],['Beşerî Sistemler','Yerleşme, hiyerarşi ve akıllı şehirler.'],['Ekonomik Faaliyetler','Tarım 4.0, enerji, sanayi ve Endüstri 4.0.'],['Afetler ve Çevre','İklim değişikliği, su güvenliği ve su ayak izi.']],
  'Felsefe': [['Çevre Sorunları ve Felsefe','Çevre etiği ve insan-doğa ilişkisi.'],['Teknoloji ve Hayat','İnsan-teknoloji ilişkisi.'],['Akıl ve İnanç','Felsefi argümanlar ve inanç.'],['Edebiyat ve Felsefe','Edebî metinlerde felsefi düşünce.'],['Hayatın Anlamı','Mutluluk, ölüm, özgürlük ve amaç.'],['Hukuk ve Felsefe','Adalet, hak ve özgürlük.']],
  'Din Kültürü': [['Kader, İrade ve Sorumluluk','Kader, kaza, irade ve tevekkül.'],['Din, Felsefe, Bilim ve Sanat','Din-bilim-sanat ilişkisi.'],['İslam Medeniyeti','Gönül coğrafyamız ve kültür.'],['İnançla İlgili Meseleler','Akıl ve güncel inanç meseleleri.'],['Yahudilik ve Hristiyanlık','Temel inançlar ve karşılaştırma.']]
};
