const Pomodoro = {
  tick: null,
  alarm(){try{const ctx=new (window.AudioContext||window.webkitAudioContext)(),beep=(at,freq)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.001,at);g.gain.exponentialRampToValueAtTime(.22,at+.03);g.gain.exponentialRampToValueAtTime(.001,at+.32);o.connect(g);g.connect(ctx.destination);o.start(at);o.stop(at+.34)};ctx.resume().then(()=>{const now=ctx.currentTime;beep(now,740);beep(now+.42,880);beep(now+.84,1040);setTimeout(()=>ctx.close(),1600)})}catch(e){}},
  state() { return DB.user().pomodoro||{end:null,duration:25*60,active:false}; },
  start(minutes,resume=false) { const previous=this.state(),chosen=minutes*60,remaining=resume&&!previous.active&&previous.end===null&&previous.duration>0?previous.duration:chosen,s={end:Date.now()+remaining*1000,duration:remaining,active:true}; DB.update({pomodoro:s}); window.Community?.syncPresence(); this.run(); App.render(); },
  stop() { const s=this.state(); s.duration=Math.max(0,Math.ceil((s.end-Date.now())/1000)); s.active=false;s.end=null; DB.update({pomodoro:s}); window.Community?.syncPresence(); clearInterval(this.tick);App.render(); },
  reset() { DB.update({pomodoro:{end:null,duration:25*60,active:false}});window.Community?.syncPresence();clearInterval(this.tick);App.render(); },
  run() { clearInterval(this.tick); this.tick=setInterval(()=>{ const s=this.state(); if(!s.active)return clearInterval(this.tick); const left=Math.ceil((s.end-Date.now())/1000); const el=document.querySelector('#pomo-display');if(el)el.textContent=App.time(left);if(left%15===0)window.Community?.syncPresence();if(left<=0){clearInterval(this.tick);DB.update({pomodoro:{end:null,duration:25*60,active:false},studyLogs:[...DB.user().studyLogs,{id:DB.uid(),minutes:Math.round(s.duration/60),date:new Date().toISOString()}]});window.Community?.syncPresence();this.alarm();App.toast('Pomodoro tamamlandı! Harika iş.');App.render()} },500); },
  remaining() { const s=this.state(); return s.active?Math.max(0,Math.ceil((s.end-Date.now())/1000)):s.duration; }
};
